{"name": "Авторизаиция с недействительными учетными данными", "status": "failed", "statusDetails": {"message": "AssertionError: assert 'Invalid credentials. Please try again.' != 'Invalid credentials. Please try again.'\n +  where 'Invalid credentials. Please try again.' = get_error_message()\n +    where get_error_message = <project.pages.login_page.LoginPage object at 0x000001B44EDB7010>.get_error_message", "trace": "login_page = <project.pages.login_page.LoginPage object at 0x000001B44EDB7010>\n\n    @allure.feature('Авторизаци')\n    @allure.story('Авторизации недействительные учетные данные')\n    @allure.severity(allure.severity_level.CRITICAL)\n    @allure.title('Авторизаиция с недействительными учетными данными')\n    def test_login_failure(login_page):\n        with allure.step('Открыть страницу авторизации'):\n            login_page.navigate()\n        with allure.step('Ввести в форму авторизации недействительные учетные данные'):\n            login_page.login('invalid_user', 'invalid_password')\n        with allure.step('Отображается ошибка - Invalid credentials. Please try again.'):\n>           assert login_page.get_error_message() != 'Invalid credentials. Please try again.'\nE           AssertionError: assert 'Invalid credentials. Please try again.' != 'Invalid credentials. Please try again.'\nE            +  where 'Invalid credentials. Please try again.' = get_error_message()\nE            +    where get_error_message = <project.pages.login_page.LoginPage object at 0x000001B44EDB7010>.get_error_message\n\nproject\\tests\\test_login.py:18: AssertionError"}, "steps": [{"name": "Открыть страницу авторизации", "status": "passed", "start": 1745688370140, "stop": 1745688371053}, {"name": "Ввести в форму авторизации недействительные учетные данные", "status": "passed", "start": 1745688371053, "stop": 1745688371274}, {"name": "Отображается ошибка - Invalid credentials. Please try again.", "status": "failed", "statusDetails": {"message": "AssertionError: assert 'Invalid credentials. Please try again.' != 'Invalid credentials. Please try again.'\n +  where 'Invalid credentials. Please try again.' = get_error_message()\n +    where get_error_message = <project.pages.login_page.LoginPage object at 0x000001B44EDB7010>.get_error_message\n", "trace": "  File \"C:\\Users\\Elshad\\PycharmProjects\\playwright\\project\\tests\\test_login.py\", line 18, in test_login_failure\n    assert login_page.get_error_message() != 'Invalid credentials. Please try again.'\n"}, "start": 1745688371274, "stop": 1745688371296}], "parameters": [{"name": "browser_name", "value": "'chromium'"}], "start": 1745688370140, "stop": 1745688371298, "uuid": "892b283e-233d-491d-94c5-124450a63ade", "historyId": "3230c37a4ddf37e226b736e144aaba65", "testCaseId": "89a909a1ca222b871b75e39c89c26fa1", "fullName": "tests.test_login#test_login_failure", "labels": [{"name": "story", "value": "Авторизации недействительные учетные данные"}, {"name": "feature", "value": "Авторизаци"}, {"name": "severity", "value": "critical"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "host", "value": "Elshad27"}, {"name": "thread", "value": "11420-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}