{"name": "Авторизаиция с недействительными учетными данными", "status": "failed", "statusDetails": {"message": "AssertionError: assert 'Invalid credentials. Please try again.' != 'Invalid credentials. Please try again.'\n +  where 'Invalid credentials. Please try again.' = get_error_message()\n +    where get_error_message = <project.pages.login_page.LoginPage object at 0x000002A2E9808D90>.get_error_message", "trace": "login_page = <project.pages.login_page.LoginPage object at 0x000002A2E9808D90>\n\n    @allure.feature('Авторизаци')\n    @allure.story('Авторизации недействительные учетные данные')\n    @allure.severity(allure.severity_level.CRITICAL)\n    @allure.title('Авторизаиция с недействительными учетными данными')\n    def test_login_failure(login_page):\n        with allure.step('Открыть страницу авторизации'):\n            login_page.navigate()\n        with allure.step('Ввести в форму авторизации недействительные учетные данные'):\n            login_page.login('invalid_user', 'invalid_password')\n        with allure.step('Отображается ошибка - Invalid credentials. Please try again.'):\n>           assert login_page.get_error_message() != 'Invalid credentials. Please try again.'\nE           AssertionError: assert 'Invalid credentials. Please try again.' != 'Invalid credentials. Please try again.'\nE            +  where 'Invalid credentials. Please try again.' = get_error_message()\nE            +    where get_error_message = <project.pages.login_page.LoginPage object at 0x000002A2E9808D90>.get_error_message\n\nproject\\tests\\test_login.py:18: AssertionError"}, "steps": [{"name": "Открыть страницу авторизации", "status": "passed", "start": 1745688984895, "stop": 1745688985698}, {"name": "Ввести в форму авторизации недействительные учетные данные", "status": "passed", "start": 1745688985698, "stop": 1745688985835}, {"name": "Отображается ошибка - Invalid credentials. Please try again.", "status": "failed", "statusDetails": {"message": "AssertionError: assert 'Invalid credentials. Please try again.' != 'Invalid credentials. Please try again.'\n +  where 'Invalid credentials. Please try again.' = get_error_message()\n +    where get_error_message = <project.pages.login_page.LoginPage object at 0x000002A2E9808D90>.get_error_message\n", "trace": "  File \"C:\\Users\\Elshad\\PycharmProjects\\playwright\\project\\tests\\test_login.py\", line 18, in test_login_failure\n    assert login_page.get_error_message() != 'Invalid credentials. Please try again.'\n"}, "start": 1745688985835, "stop": 1745688985854}], "parameters": [{"name": "browser_name", "value": "'chromium'"}], "start": 1745688984895, "stop": 1745688985854, "uuid": "f4a0ad47-2e1c-4409-9edb-33ec7e5aabe7", "historyId": "52dd5e443a4327205ac3e24e0cce2b5f", "testCaseId": "13d95e88f7b04b2652fa56f1745d5cd6", "fullName": "project.tests.test_login#test_login_failure", "labels": [{"name": "severity", "value": "critical"}, {"name": "story", "value": "Авторизации недействительные учетные данные"}, {"name": "feature", "value": "Авторизаци"}, {"name": "parentSuite", "value": "project.tests"}, {"name": "suite", "value": "test_login"}, {"name": "host", "value": "Elshad27"}, {"name": "thread", "value": "11316-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "project.tests.test_login"}]}